// Purpose: Render the default Dali social preview for public pages and solution links.
// Scope: Shared Open Graph image generated by the Next.js metadata pipeline.
import { ImageResponse } from "next/og";

export const alt = "Dali AI agent systems for real operations";
export const size = {
  width: 1200,
  height: 630,
};
export const contentType = "image/png";

export default function OpenGraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          display: "flex",
          width: "100%",
          height: "100%",
          padding: "42px",
          background: "#111312",
          color: "#111312",
          fontFamily: "Arial, Helvetica, sans-serif",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
            width: "100%",
            background: "#FCFCFA",
            padding: "50px 56px",
          }}
        >
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              fontSize: 24,
              letterSpacing: "0.18em",
              textTransform: "uppercase",
            }}
          >
            <span>Dali</span>
            <span>AI agent systems</span>
          </div>

          <div
            style={{
              display: "flex",
              alignItems: "flex-end",
              gap: 56,
            }}
          >
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                width: 640,
              }}
            >
              <span
                style={{
                  marginBottom: 18,
                  color: "#1E3A8A",
                  fontSize: 22,
                  letterSpacing: "0.2em",
                  textTransform: "uppercase",
                }}
              >
                Solution pilots
              </span>
              <div
                style={{
                  display: "flex",
                  flexDirection: "column",
                  fontSize: 62,
                  lineHeight: 0.96,
                  letterSpacing: "-0.045em",
                  textTransform: "uppercase",
                }}
              >
                <span>One workflow.</span>
                <span>Fixed first.</span>
              </div>
            </div>

            <div
              style={{
                display: "flex",
                flexDirection: "column",
                width: 280,
              border: "2px solid #111312",
              }}
            >
              {["Input", "Agent", "Approved action"].map((label, index) => (
                <div
                  key={label}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    borderBottom:
                      index < 2 ? "2px solid #111312" : "0 solid transparent",
                    padding: "18px 20px",
                    fontSize: 20,
                    textTransform: "uppercase",
                  }}
                >
                  <span>0{index + 1}</span>
                  <span>{label}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    ),
    size,
  );
}
